ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.routeserver.SerializationKt.configureSerialization
      - com.example.routeserver.ResourcesKt.configureResources
      - com.example.routeserver.RoutingKt.configureRouting
