ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.routeserver.plugins.DatabaseKt.configureDatabaseConnection
      - com.example.routeserver.plugins.SerializationKt.configureSerialization
      - com.example.routeserver.plugins.ResourcesKt.configureResources
      - com.example.routeserver.plugins.RoutingKt.configureRouting
